# This is a test workflow to gt started with Actions

name: Docker Build and Push

# Action trigger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Action job

jobs:
  # Job name
  build:
    # Job runner
    runs-on: ubuntu-latest

    # Job steps - squence of tasks
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/python-helloworld:latest
